FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements-outbox-service.txt .
RUN pip install --no-cache-dir -r requirements-outbox-service.txt

COPY app ./app
COPY outbox_api ./outbox_api
COPY migrations ./migrations

EXPOSE 8010
CMD ["python", "-m", "uvicorn", "outbox_api.main:app", "--host", "0.0.0.0", "--port", "8010"]
